version: "3"

services:
  elasticsearch:
    image: elasticsearch:6.8.0
    expose:
      - 9200
      - 9300
    restart: always

  mapbender-logstash:
    image: logstash:6.8.0
    depends_on:
      - elasticsearch
    command: ["-e", 'input { tcp { port => 9500 codec => line } } filter { grok { match => { "message" => "%{COMBINEDAPACHELOG}" }} } output { elasticsearch { index => "meetup-mapbender-%{+YYYY.MM.dd}" hosts => ["elasticsearch:9200"] } }']
    expose:
      - 9500
    ports:
      - "9500:9500"
    restart: always

  kibana:
    image: kibana:6.8.0
    expose:
      - 5601
    ports:
      - 127.0.0.1:5601:5601
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
      - kibana-logstash
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:9501"
    restart: always


  mapbender:
    image: yagajs/mapbender3
    depends_on:
      - mapbender-logstash
    ports:
      - "127.0.0.1:8080:80"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:9500"
    restart: always


  kibana-logstash:
    image: logstash:6.8.0
    command: ["-e", 'input { tcp { port => 9500 codec => line } } filter { grok { match => { "message" => "<%{POSINT:tag}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{GREEDYDATA:containerId}: %{GREEDYDATA:syslog_message}" } } json { source => "syslog_message" target => "doc"} } output { elasticsearch { index => "meetup-kibana-%{+YYYY.MM.dd}" hosts => ["elasticsearch:9200"] } }']
    depends_on:
      - elasticsearch
    expose:
      - 9500
    ports:
      - 9501:9500
    restart: always


#

